### PR TITLE
Features/av throttle

### PR DESCRIPTION
**Pull request by CodemanCodes**
This closes issue #23 .

Currently storing the throttle value in the env file, once admin page is being built out and settings are stored in db it should be easily moved.

Before entering the av command handler adding a check to see if the throttle time value has passed or if the user issuing the command is a mod or the broadcaster.

### CODE REVIEW

**Review by michaeljolley — COMMENTED** [review]
You know how we do.  Looks great though.  Especially with the amazing detail that I provided. 

bitmoji

Reference 2019-08-08 stream around 1:45

**Comment by CodemanCodes** [comment]
Updated to throttle per user instead of chat-wide. Mods & Broadcaster are not throttled

**Review by michaeljolley — APPROVED** [review]
Thank you a ton!  Great work!

**Comment by michaeljolley** [comment]
bitmoji

**Pull request merged**
