### PR TITLE
The chat service will now auto-announce live-coders team members. Closes #41

### LINKED ISSUE #41: Auto shoutout
Implement  auto shout of when other live coders enter chat

### PR DESCRIPTION
**Pull request by parithon**
# Purpose

There was a question / feature request to have the chatbot auto announce live-coder team members. This PR seeks to solve that feature request.

# How it works

> DISCLAIMER: Unfortunately the 'Helix' Twitch APIs do not have an endpoint to retrieve Twitch Team information. However, the 'Kraken' APIs do have an endpoint. Although 'Kraken' is deprecated, I felt it was Ok to use it's API because 'Helix' has no alternative and Kraken still works today.

1. **chron** service starts, then waits 15 seconds and calls the **api** service for the live-coders team information.
2. **api** service sends a request to the Kraken API for information on the live-coders team.
3. **api** service receives the response from the Kraken API ~~and sends the information over the Socket.~~ and sends a response payload back to the **chron** service with the results.
4. ~~**hub** service listens for the event, pulls out the 'users' array from the live-coders team then re-submits the information over its io socket.~~ **chron** pulls out the team member data from and posts the information to the **user** service to update the live-coders team members.
5. ~~**chat** service listens for the event and saves the list of members in memory as `liveCodersTeamMembers`.~~ **user** service listens for the post and fires off a request to the **api** service to get the twitch user information from the **helix** api in batches of 100. The **api** service sends a response payload back to the **user** service with the gathered information.
6. ~~**chat** service listens for 'chat' events and checks the user against the `liveCodersTeamMembers` list, and if the individual both exists on the team AND has not already been announce for this stream, **chat** will send out a shoutout.~~ **user** service updates the users `liveCodersTeamMember` and saves the record in the database and to the cache.

Closes #41

### CODE REVIEW

**Comment by parithon** [comment]
@MichaelJolley mentioned on chat that he received an email which had a hard cutoff date but couldn't remember if that was for the v3 or v5 APIs. I believe the email was referring to the shutdown of v3, not v5 (Helix), which is still being used as the migration path for v3 API developers. v5 is deprecated, but a shutdown timeframe is still unknown.

Here are the developer announcements:
- [Twitch API v3 Shutdown Timeline](https://discuss.dev.twitch.tv/t/twitch-api-v3-shutdown-timeline/21931)
- [Twitch API v3 and v5 Deprecation Updates](https://discuss.dev.twitch.tv/t/twitch-api-v3-and-v5-deprecation-updates/19144)

**Review by michaeljolley — CHANGES_REQUESTED** [review]
Fix this garbage yo.  (I kid in love)

**Comment by michaeljolley** [comment]
Ha!  Just realized I wrote garbage above.  I clearly remember things I say/do so well.

**Comment by parithon** [comment]
bitmoji

I cleaned up the place. Hopefully, it passes muster!

**Review by michaeljolley — APPROVED** [review]

**Pull request merged**
